---
- name: Install dnf-plugins-core to enable using copr repositories
  become: true
  dnf:
      name: dnf-plugins-core
      state: present

- name: Enable leapp repository
  become: true
  raw: "dnf copr enable -y {{ snactor.repository }}"

- name: Install leapp snactor
  become: true
  dnf:
      name: "{{ snactor.package }}"
      state: present

- name: Create snactor conf file
  file:
      path: "{{ snactor.conf_file }}"
      state: touch
      mode: 0644
