daemon:
    build_steps:
        - name: install-deps
          become: false         ## All deps are installed in ~/go
        - name: build
          become: false
        - name: install
          become: true
    git:
        repo: github.com/leapp-to/leapp-go
    link:
        src: "{{ lookup('env', 'HOME') }}/go/src/github.com/leapp-to/leapp-go"
        dest: "{{ common.paths.workdir }}/leapp-go"
    packages:
        common:
            - golang
            - golang-googlecode-tools-goimports
        fedora:
            - golint
    missing:
        centos:
            - github.com/golang/lint/golint
