---
- name: Get leapp actors main repository
  git:
      repo: "{{ actors.repo }}"
      dest: "{{ actors.dest }}"

- name: Install packages required by some actors, if necessary
  become: true
  dnf:
      name: "{{ item }}"
      state: present
  with_items: "{{ actors.packages }}"

- name: Add actors_dir to snactor conf file
  lineinfile:
      path: "{{ snactor.conf_file }}"
      regexp: "^actors_dir:"
      line: "actors_dir: {{ actors.actors_path }}"

- name: Add schemas_dir to snactor conf file
  lineinfile:
      path: "{{ snactor.conf_file }}"
      regexp: "^schemas_dir:"
      line: "schemas_dir: {{ actors.schemas_path }}"
